apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    {{- if empty .Values.service.targetPort }}
    targetPort: {{ .Values.service.port }}
    {{- else }}
    targetPort: {{ .Values.service.targetPort }}
    {{- end }}
  
  selector:
    app: techtrends
  
  type: {{ .Values.service.type }}